### ISSUE TITLE
Participants of justaskdavidb should know general information about creating Issue Templates in GitHub repositories

### ISSUE THREAD

**Issue by jasalise** [inDevelopme/justaskdavidb#72]
- Description of the issue- Need to know how to create issue templates in Github
- justaskdavidb does not support or have issue templates 
- Expected behavior- Need to know how to created the template and justaskdavidb will be able to use these templates to create future issues
- How to replicate the problem: 
- click issue tab
- select create new issue
- blank issue ticket appears
- also needed provide a solution (include file structure, desired file name for template, sections I want in the template) 
- use simwire plus output from chatgpt for the content that needs to be in here.

### Issue Template 

**Describe the issue**
Need to know how to create issue templates in Github.
Justaskdavidb does not support or have issue templates.

**To Reproduce** 
1. Go to [GitHub Justaskdavidb](https://github.com/inDevelopme/justaskdavidb)
2. Click 'Issues'
3. Click 'New Issue'
4. See blank issue ticket appear 

**Expected behavior**
Need to know how to create the templates and participants of justaskdavidb will be able to use these templates to create future issues

**Screenshots**
<img width="1452" alt="Screenshot 2024-06-07 at 6 09 03 PM" src="https://github.com/inDevelopme/justaskdavidb/assets/163200867/499d1742-56da-435f-a0e0-71d7b52c590d">

**Environment (please complete the following information):**
- OS: [MacOS]
- Browser [Safari]

**Solution**
File Structure- Markdown
Desired file name for template- Issuetemplate.md
Sections I want in the template ??

use simwire plus output from chatgpt for the content that needs to be in here??

**Comment by andrew-zhouu** [comment]
# Creating an Issue Template

## How to Add a Template to Your Repository

### 1. Create a `.github` Directory:
   - Navigate to your repository on GitHub.
   - Click on the "Add file" button and choose "Create new file."
   - Name the file `.github/ISSUE_TEMPLATE/bug_report.md` for a bug report, or use a different name for other types of issues.

### 2. Add the Template Content:
   - Copy and paste the template content into the file.
   - Adjust the template according to the needs of your project.

### 3. Commit the File:
   - Scroll down and add a commit message.
   - Click "Commit new file" to add the template to your repository.

**Once you've added the template, GitHub will use it whenever someone creates a new issue.**


## Bug Report Issue Template Example


### 1. Description

-- Provide a clear and concise description of the issue. --

### 2. Steps to Reproduce

-- List the steps to reproduce the issue. If applicable, include code snippets or commands. --

**1.** --------------- Step 1 -------------------
**2.** --------------- Step 2 -------------------
**3.** --------------- Step 3 -------------------

### 3. Expected Behavior

-- Describe what you expected to happen. --

### 4. Actual Behavior

--  Describe what actually happened. --

### 5. Screenshots

-- If applicable, add screenshots to help explain the problem. --

### 6. Environment

- **Operating System**: [e.g., Windows 10, macOS 11.4]
- **Browser/Version**: [e.g., Chrome 91, Firefox 89]
- **Version**: [e.g., 1.2.3]

### 7. Additional Context

-- Add any other context about the issue here. For example, was this issue occurring only in a specific scenario or after a specific event? --

### 8. Suggested Fix

-- If you have an idea for how to fix the issue, include it here. --

### 9. Labels

-- Add any relevant labels or tags that may help in categorizing the issue. --

### 10. Assignees

-- Assign to someone if you know who should handle this issue --



# Creating a new issue

### 1. **Create a New Issue**

1. **Click New Issue**: On the Issues page, you’ll see a button labeled **New issue**. Click it to start creating a new issue.

### 2. **Fill Out the Issue Form**

1. **Title**: Enter a descriptive title for your issue in the “Title” field. This should give a brief overview of the problem or suggestion.
2. **Description**: In the larger text box, provide a detailed description of the issue. Be as specific as possible. Include steps to reproduce the issue, expected behavior, actual behavior, and any other relevant information. If applicable, you can also include screenshots, logs, or code snippets.

### 3. **Add Labels, Assignees, and Milestones**

1. **Labels**: You can categorize the issue by adding labels. These can indicate the type of issue (e.g., bug, enhancement) or its priority.
2. **Assignees**: If you know who should handle the issue, you can assign it to a specific user.
3. **Milestones**: If your repository uses milestones to track progress toward goals, you can assign the issue to a milestone.

### 4. **Submit the Issue**

1. **Click Submit New Issue**: Once you’ve filled out the form, click the **Submit new issue** button to create the issue.

## Tips for Creating Effective Issues

- **Be Clear and Specific**: Provide all necessary details to help maintainers understand and address the issue efficiently.
- **Provide Context**: Mention any relevant information that could help in resolving the issue.
- **Follow Templates**: Some repositories have issue templates that you should follow. These templates help ensure that all necessary information is provided.

**Comment by andrew-zhouu** [comment]
> # Creating an Issue Template
> ## How to Add a Template to Your Repository
> ### 1. Create a `.github` Directory:
> * Navigate to your repository on GitHub.
> * Click on the "Add file" button and choose "Create new file."
> * Name the file `.github/ISSUE_TEMPLATE/bug_report.md` for a bug report, or use a different name for other types of issues.
> 
> ### 2. Add the Template Content:
> * Copy and paste the template content into the file.
> * Adjust the template according to the needs of your project.
> 
> ### 3. Commit the File:
> * Scroll down and add a commit message.
> * Click "Commit new file" to add the template to your repository.
> 
> **Once you've added the template, GitHub will use it whenever someone creates a new issue.**
> 
> ## Bug Report Issue Template Example
> ### 1. Description
> -- Provide a clear and concise description of the issue. --
> 
> ### 2. Steps to Reproduce
> -- List the steps to reproduce the issue. If applicable, include code snippets or commands. --
> 
> **1.** --------------- Step 1 ------------------- **2.** --------------- Step 2 ------------------- **3.** --------------- Step 3 -------------------
> 
> ### 3. Expected Behavior
> -- Describe what you expected to happen. --
> 
> ### 4. Actual Behavior
> -- Describe what actually happened. --
> 
> ### 5. Screenshots
> -- If applicable, add screenshots to help explain the problem. --
> 
> ### 6. Environment
> * **Operating System**: [e.g., Windows 10, macOS 11.4]
> * **Browser/Version**: [e.g., Chrome 91, Firefox 89]
> * **Version**: [e.g., 1.2.3]
> 
> ### 7. Additional Context
> -- Add any other context about the issue here. For example, was this issue occurring only in a specific scenario or after a specific event? --
> 
> ### 8. Suggested Fix
> -- If you have an idea for how to fix the issue, include it here. --
> 
> ### 9. Labels
> -- Add any relevant labels or tags that may help in categorizing the issue. --
> 
> ### 10. Assignees
> -- Assign to someone if you know who should handle this issue --
> 
> # Creating a new issue
> ### 1. **Create a New Issue**
> 1. **Click New Issue**: On the Issues page, you’ll see a button labeled **New issue**. Click it to start creating a new issue.
> 
> ### 2. **Fill Out the Issue Form**
> 1. **Title**: Enter a descriptive title for your issue in the “Title” field. This should give a brief overview of the problem or suggestion.
> 2. **Description**: In the larger text box, provide a detailed description of the issue. Be as specific as possible. Include steps to reproduce the issue, expected behavior, actual behavior, and any other relevant information. If applicable, you can also include screenshots, logs, or code snippets.
> 
> ### 3. **Add Labels, Assignees, and Milestones**
> 1. **Labels**: You can categorize the issue by adding labels. These can indicate the type of issue (e.g., bug, enhancement) or its priority.
> 2. **Assignees**: If you know who should handle the issue, you can assign it to a specific user.
> 3. **Milestones**: If your repository uses milestones to track progress toward goals, you can assign the issue to a milestone.
> 
> ### 4. **Submit the Issue**
> 1. **Click Submit New Issue**: Once you’ve filled out the form, click the **Submit new issue** button to create the issue.
> 
> ## Tips for Creating Effective Issues
> * **Be Clear and Specific**: Provide all necessary details to help maintainers understand and address the issue efficiently.
> * **Provide Context**: Mention any relevant information that could help in resolving the issue.
> * **Follow Templates**: Some repositories have issue templates that you should follow. These templates help ensure that all necessary information is provided.

I will add more information later, including desired standard file name and more visual sources, such as screenshots, to help participants thoroughly understand the process of creating an issue template.

**Comment by Tre2k3** [comment]
This issue was detailed and easy to follow! One suggestion I have is:

- The “Sections I want in the template” part in the **Solution** still has question marks — Perhaps suggest Sections to fulfill this request.
